In [61]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

import warnings
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_csv("combined.csv")
df.head()

,model,model_year,milage,fuel_type,transmission,ext_col,car/sedan,condition,location,no_of_seats,cc,power_steering,push_start,power_seat,price
0,vitz,1999,167000,petrol,automatic,brown,car,medium,hikkaduwa,5,1000,yes,no,no,"3,500,000"
1,aqua,2013,91000,petrol,automatic,light blue,car,mint,kurunegala,5,1500,yes,yes,no,"6,800,000.00"
2,aqua urban,2015,117000,hybrid,automatic,black,car,mint,kadawatha,5,1500,yes,yes,no,"8,490,000.00"
3,vitz,2018,84000,petrol,automatic,white,car,high,negombo,5,1000,yes,yes,no,"7,800,000"
4,Toyota Premio G superior,2013,48900,petrol,automatic,pearl white,sedan,mint,ragama,5,1500,yes,yes,yes,"11,500,000.00"

In [3]:
df.shape

(597, 15)

In [4]:
df.head(2)

,model,model_year,milage,fuel_type,transmission,ext_col,car/sedan,condition,location,no_of_seats,cc,power_steering,push_start,power_seat,price
0,vitz,1999,167000,petrol,automatic,brown,car,medium,hikkaduwa,5,1000,yes,no,no,"3,500,000"
1,aqua,2013,91000,petrol,automatic,light blue,car,mint,kurunegala,5,1500,yes,yes,no,"6,800,000.00"

In [5]:
import datetime

current_year=datetime.datetime.now().year
df["age"]=current_year-df["model_year"].astype(int)
df.head(2)

,model,model_year,milage,fuel_type,transmission,ext_col,car/sedan,condition,location,no_of_seats,cc,power_steering,push_start,power_seat,price,age
0,vitz,1999,167000,petrol,automatic,brown,car,medium,hikkaduwa,5,1000,yes,no,no,"3,500,000",27
1,aqua,2013,91000,petrol,automatic,light blue,car,mint,kurunegala,5,1500,yes,yes,no,"6,800,000.00",13

In [6]:
df.shape

(597, 16)

In [7]:
df.isnull().sum()

model             0
model_year        0
milage            0
fuel_type         0
transmission      0
ext_col           0
car/sedan         0
condition         0
location          0
no_of_seats       0
cc                0
power_steering    0
push_start        0
power_seat        0
price             0
age               0
dtype: int64

In [8]:
df["model"].value_counts()

model
yaris                             93
Corolla 121 g grade               58
vitz                              53
aqua                              53
Toyota Premio G superior          49
Toyota Premio                     47
Toyota Axio G Grade               39
Toyota Axio WXB                   26
aqua urban                        25
vitz safety                       19
Toyota Axio WXB                   18
Corolla 121 x grade               18
vitz safety                       15
Corolla 121 lx grade              14
Toyota Axio G Grade               13
vitz                              11
aqua                              11
Corolla 121 xli grade              8
yaris                              7
aqua x urban                       5
Toyota Premio                      3
 Corolla 121 x grade               2
aqua urban                         2
Toyota Axio Wxb Limited Editio     1
Toyota Axio Wxb                    1
Toyota AXIO G Grade                1
Toyota Axio WXB anniversary        1
aqua x urban face                  1
aqua                               1
aqua x urban g                     1
vits safety                        1
Name: count, dtype: int64

In [9]:
len(df["model"].value_counts())

31

In [10]:
df["model"]=df["model"].str.strip()
df["model"]=df["model"].str.lower()

In [11]:
df["model"].value_counts()

model
yaris                             100
aqua                               65
vitz                               64
corolla 121 g grade                58
toyota axio g grade                53
toyota premio                      50
toyota premio g superior           49
toyota axio wxb                    45
vitz safety                        34
aqua urban                         27
corolla 121 x grade                20
corolla 121 lx grade               14
corolla 121 xli grade               8
aqua x urban                        5
toyota axio wxb limited editio      1
toyota axio wxb anniversary         1
aqua x urban face                   1
aqua x urban g                      1
vits safety                         1
Name: count, dtype: int64

In [12]:
model_map = {
    "vits safety": "vitz safety",
    "toyota axio wxb": "toyota axio wxb",
    "toyota axio wxb limited editio": "toyota axio wxb",
    "aqua x urban g": "aqua x urban",
    "aqua x urban face": "aqua x urban",
    "corolla 121 x grade": "corolla 121 x grade",
    "yaris": "yaris"
}

df["model"] = df["model"].replace(model_map)

In [13]:
model_map = {
    "toyota axio wxb anniversary":"toyota axio wxb",
    "corolla 121 xli grade":"corolla 121 lx grade",
    "aqua x urban":"aqua urban"
}

df["model"] = df["model"].replace(model_map)

In [14]:
df["model"].value_counts()

model
yaris                       100
aqua                         65
vitz                         64
corolla 121 g grade          58
toyota axio g grade          53
toyota premio                50
toyota premio g superior     49
toyota axio wxb              47
vitz safety                  35
aqua urban                   34
corolla 121 lx grade         22
corolla 121 x grade          20
Name: count, dtype: int64

In [15]:
len(df["model"].value_counts())

12

In [16]:
df["fuel_type"].value_counts()

fuel_type
petrol    433
hybrid    156
diesel      8
Name: count, dtype: int64

In [17]:
df["transmission"].value_counts()

transmission
automatic     571
manual         22
 automatic      3
atomatic        1
Name: count, dtype: int64

In [18]:
transmission_map = {
    " automatic": "automatic",
    "atomatic": "automatic",
}

df["transmission"] = df["transmission"].replace(transmission_map)

In [19]:
df["transmission"].value_counts()

transmission
automatic    575
manual        22
Name: count, dtype: int64

In [20]:
df["ext_col"].value_counts()

ext_col
white                     131
black                     114
pearl white                53
wine red                   42
dark blue                  32
red                        29
super white                24
desert sand mica           24
ash                        23
lunar mist                 14
grey                       10
blue                        9
brown                       9
impulse red                 9
light blue                  7
maroon                      7
indigo ink                  5
dark brown                  5
silver                      4
dark maroon                 4
green                       4
impulse red                 3
indigo ink peal             3
orange                      3
light green                 3
dark purple                 3
metallic green              2
olive green                 2
gray                        2
impulse red pearl           2
silver metallic             2
dark metallic green         2
heather metallic            1
light brown                 1
golden yellow               1
metallic silver             1
elegant light green         1
gray                        1
dark red                    1
dark red                    1
antique silver metalic      1
grey mica                   1
light gray                  1
Name: count, dtype: int64

In [21]:
color_counts = df["ext_col"].value_counts()

df["ext_col"] = df["ext_col"].apply(
    lambda x: x if color_counts[x] >= 10 else "others"
)

In [22]:
df["ext_col"].value_counts()

ext_col
white               131
black               114
others              101
pearl white          53
wine red             42
dark blue            32
red                  29
desert sand mica     24
super white          24
ash                  23
lunar mist           14
grey                 10
Name: count, dtype: int64

In [23]:
df["ext_col"].value_counts()

ext_col
white               131
black               114
others              101
pearl white          53
wine red             42
dark blue            32
red                  29
desert sand mica     24
super white          24
ash                  23
lunar mist           14
grey                 10
Name: count, dtype: int64

In [24]:
df["car/sedan"].value_counts()

car/sedan
sedan    299
car      296
car        2
Name: count, dtype: int64

In [25]:
df["car/sedan"].unique()

array(['car', 'sedan', 'car '], dtype=object)

In [26]:
type_map = {
    "car ": "car",
}

df["car/sedan"] = df["car/sedan"].replace(type_map)

In [27]:
df["car/sedan"].value_counts()

car/sedan
sedan    299
car      298
Name: count, dtype: int64

In [28]:
df["condition"].value_counts()

condition
mint      405
medium    104
high       87
high        1
Name: count, dtype: int64

In [29]:
condition_map = {
    "high ": "mint",
    "high":"mint"
}

df["condition"] = df["condition"].replace(condition_map)

In [30]:
df["condition"].value_counts()

condition
mint      493
medium    104
Name: count, dtype: int64

In [31]:
len(df["location"].value_counts())

99

In [32]:
pd.set_option("display.max_rows", None)
df["location"].value_counts()

location
colombo                    109
kandy                       36
gampaha                     33
kurunegala                  23
matara                      23
galle                       19
homagama                    13
piliyandala                 13
kadawatha                   13
nugegoda                    12
polonnaruwa                 12
rathnapura                  12
panadura                    11
kaluthara                   11
malabe                      11
maharagama                  10
kurunagala                  10
kottawa                      8
nittambuwa                   8
katunayake                   8
battaramulla                 8
wennappuwa                   7
pannipitiya                  7
negombo                      7
dehiwala                     7
kuliyapitiya                 7
kegalle                      6
kaduwela                     5
horana                       5
moratuwa                     5
ragama                       5
chilaw                       5
kelaniya                     4
matale                       4
ambalangoda                  4
moneragala                   4
hambantota                   4
negambo                      3
ja-ela                       3
anuradhapura                 3
ratnapura                    3
dehiwala-mount-lavinia       3
hambanthota                  3
bandaragama                  3
badulla                      3
matugama                     3
pannala                      3
boralesgamuwa                3
kalutara                     3
middeniya                    2
bandarawela                  2
ja ela                       2
embilipitiya                 2
dambulla                     2
kesbewa                      2
Kurunegala                   2
boralasgamuwa                2
monaragala                   2
trincomalee                  2
veyangoda                    2
hikkaduwa                    2
minuwangoda                  2
nawala                       2
wattala                      2
puttalama                    2
divulapitiya                 2
marawila                     2
batticaloa                   2
tangalle                     2
kiribathgoda                 2
dehiwala mount laviniya      2
kandana                      1
mulleriyawa                  1
nattandiya                   1
kadawathe                    1
ballicaloa                   1
dompe                        1
embilipitya                  1
pannopitiya                  1
hanwella                     1
Divulapitiya                 1
rajagiriya                   1
Gampaha                      1
kalmunai                     1
padukka                      1
meerigama                    1
anuradapura                  1
kesbawa                      1
balangoda                    1
warakapola                   1
jaffna                       1
elpitiya                     1
nuwara eliya                 1
 nuwara eliya                1
hendala                      1
colombo 7                    1
kotte                        1
welimada                     1
mawanella                    1
Name: count, dtype: int64

In [33]:
location_counts = df["location"].value_counts()

df["location"] = df["location"].apply(
    lambda x: x if location_counts[x] >= 10 else "others"
)

In [34]:
df["location"].value_counts()

location
others         226
colombo        109
kandy           36
gampaha         33
kurunegala      23
matara          23
galle           19
piliyandala     13
homagama        13
kadawatha       13
rathnapura      12
polonnaruwa     12
nugegoda        12
malabe          11
kaluthara       11
panadura        11
kurunagala      10
maharagama      10
Name: count, dtype: int64

In [35]:
len(df["location"].value_counts())

18

In [36]:
type(df["price"])

pandas.core.series.Series

In [37]:
df.dtypes

model             object
model_year         int64
milage            object
fuel_type         object
transmission      object
ext_col           object
car/sedan         object
condition         object
location          object
no_of_seats        int64
cc                 int64
power_steering    object
push_start        object
power_seat        object
price             object
age                int32
dtype: object

In [38]:
import re

# Keep only digits
df["milage"] = df["milage"].str.replace(r"\D", "", regex=True)

In [39]:
# Remove commas or spaces if any
df["milage"] = df["milage"].str.replace(",", "").str.strip()
df["milage"] = pd.to_numeric(df["milage"])

df["price"] = df["price"].str.replace(",", "").str.strip()
df["price"] = pd.to_numeric(df["price"])

In [40]:
df.dtypes

model              object
model_year          int64
milage              int64
fuel_type          object
transmission       object
ext_col            object
car/sedan          object
condition          object
location           object
no_of_seats         int64
cc                  int64
power_steering     object
push_start         object
power_seat         object
price             float64
age                 int32
dtype: object

In [41]:
from sklearn.preprocessing import LabelEncoder

le_condition = LabelEncoder()
df["condition"] = le_condition.fit_transform(df["condition"])

In [42]:
le_transmission = LabelEncoder()
df["transmission"] = le_transmission.fit_transform(df["transmission"])

In [43]:
df[["power_steering", "push_start", "power_seat"]] = df[["power_steering", "push_start", "power_seat"]].apply(
    lambda x: x.str.strip().str.lower().map({"yes": 1, "no": 0})
)

In [44]:
df.head(2)

,model,model_year,milage,fuel_type,transmission,ext_col,car/sedan,condition,location,no_of_seats,cc,power_steering,push_start,power_seat,price,age
0,vitz,1999,167000,petrol,0,others,car,0,others,5,1000,1,0,0,3500000.0,27
1,aqua,2013,91000,petrol,0,others,car,1,kurunegala,5,1500,1,1,0,6800000.0,13

In [45]:
cat_columns = ["model", "fuel_type", "location", "car/sedan","ext_col"]
df_encoded = pd.get_dummies(df, columns=cat_columns, sparse=True).astype(int)

In [46]:
df_encoded.head(2)

,model_year,milage,transmission,condition,no_of_seats,cc,power_steering,push_start,power_seat,price,...,ext_col_dark blue,ext_col_desert sand mica,ext_col_grey,ext_col_lunar mist,ext_col_others,ext_col_pearl white,ext_col_red,ext_col_super white,ext_col_white,ext_col_wine red
0,1999,167000,0,0,5,1000,1,0,0,3500000,...,0,0,0,0,1,0,0,0,0,0
1,2013,91000,0,1,5,1500,1,1,0,6800000,...,0,0,0,0,1,0,0,0,0,0

In [47]:
df_final=df_encoded

In [48]:
pd.set_option("display.max_columns", None)

In [49]:
df_final.head(2)

,model_year,milage,transmission,condition,no_of_seats,cc,power_steering,push_start,power_seat,price,age,model_aqua,model_aqua urban,model_corolla 121 g grade,model_corolla 121 lx grade,model_corolla 121 x grade,model_toyota axio g grade,model_toyota axio wxb,model_toyota premio,model_toyota premio g superior,model_vitz,model_vitz safety,model_yaris,fuel_type_diesel,fuel_type_hybrid,fuel_type_petrol,location_colombo,location_galle,location_gampaha,location_homagama,location_kadawatha,location_kaluthara,location_kandy,location_kurunagala,location_kurunegala,location_maharagama,location_malabe,location_matara,location_nugegoda,location_others,location_panadura,location_piliyandala,location_polonnaruwa,location_rathnapura,car/sedan_car,car/sedan_sedan,ext_col_ash,ext_col_black,ext_col_dark blue,ext_col_desert sand mica,ext_col_grey,ext_col_lunar mist,ext_col_others,ext_col_pearl white,ext_col_red,ext_col_super white,ext_col_white,ext_col_wine red
0,1999,167000,0,0,5,1000,1,0,0,3500000,27,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0
1,2013,91000,0,1,5,1500,1,1,0,6800000,13,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0

In [50]:
df_final.shape

(597, 58)

In [51]:
df_final.columns

Index(['model_year', 'milage', 'transmission', 'condition', 'no_of_seats',
       'cc', 'power_steering', 'push_start', 'power_seat', 'price', 'age',
       'model_aqua', 'model_aqua urban', 'model_corolla 121 g grade',
       'model_corolla 121 lx grade', 'model_corolla 121 x grade',
       'model_toyota axio g grade', 'model_toyota axio wxb',
       'model_toyota premio', 'model_toyota premio g superior', 'model_vitz',
       'model_vitz safety', 'model_yaris', 'fuel_type_diesel',
       'fuel_type_hybrid', 'fuel_type_petrol', 'location_colombo',
       'location_galle', 'location_gampaha', 'location_homagama',
       'location_kadawatha', 'location_kaluthara', 'location_kandy',
       'location_kurunagala', 'location_kurunegala', 'location_maharagama',
       'location_malabe', 'location_matara', 'location_nugegoda',
       'location_others', 'location_panadura', 'location_piliyandala',
       'location_polonnaruwa', 'location_rathnapura', 'car/sedan_car',
       'car/sedan_sedan', 'ext_col_ash', 'ext_col_black', 'ext_col_dark blue',
       'ext_col_desert sand mica', 'ext_col_grey', 'ext_col_lunar mist',
       'ext_col_others', 'ext_col_pearl white', 'ext_col_red',
       'ext_col_super white', 'ext_col_white', 'ext_col_wine red'],
      dtype='object')

In [52]:
x=df_final.drop("price",axis=1)
y=df_final["price"]

In [53]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [54]:
x_train.shape

(477, 57)

In [55]:
x_test.shape

(120, 57)

In [56]:
!pip install xgboost

Requirement already satisfied: xgboost in c:\users\ww\appdata\local\programs\python\python310\lib\site-packages (3.2.0)
Requirement already satisfied: numpy in c:\users\ww\appdata\local\programs\python\python310\lib\site-packages (from xgboost) (1.24.4)
Requirement already satisfied: scipy in c:\users\ww\appdata\local\programs\python\python310\lib\site-packages (from xgboost) (1.15.3)

WARNING: Ignoring invalid distribution -f-keras (c:\users\ww\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -f-keras (c:\users\ww\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -f-keras (c:\users\ww\appdata\local\programs\python\python310\lib\site-packages)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [57]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor

In [58]:
model_params = {

    'linear_regression': {
        'model': LinearRegression(),
        'params': {
            'fit_intercept': [True, False]
        }
    },

    'ridge': {
        'model': Ridge(),
        'params': {
            'alpha': [0.01, 0.1, 1, 10, 50]
        }
    },

    'lasso': {
        'model': Lasso(),
        'params': {
            'alpha': [0.001, 0.01, 0.1, 1, 10]
        }
    },

    'random_forest': {
        'model': RandomForestRegressor(random_state=42),
        'params': {
            'n_estimators': [100, 200, 300],
            'max_depth': [None, 5, 10, 20],
            'min_samples_split': [2, 5, 10]
        }
    },

    'extra_trees': {
        'model': ExtraTreesRegressor(random_state=42),
        'params': {
            'n_estimators': [100, 200, 300],
            'max_depth': [None, 5, 10, 20],
            'min_samples_split': [2, 5, 10]
        }
    },

    'gradient_boosting': {
        'model': GradientBoostingRegressor(random_state=42),
        'params': {
            'n_estimators': [100, 200],
            'learning_rate': [0.01, 0.1, 0.2],
            'max_depth': [3, 5, 7]
        }
    },

    'xgboost': {
        'model': XGBRegressor(random_state=42, verbosity=0),
        'params': {
            'n_estimators': [100, 200],
            'learning_rate': [0.01, 0.1, 0.2],
            'max_depth': [3, 5, 7]
        }
    }

}

In [59]:
print(y.shape)

(597,)

In [62]:
from sklearn.model_selection import GridSearchCV

scores = []
for model_name, mp in model_params.items():
    model = GridSearchCV(
        mp['model'],
        mp['params'],
        cv=5,
        scoring='r2',
        return_train_score=False,
        n_jobs=-1 )
    
    model.fit(x_train, y_train)
    
    scores.append({
        'model': model_name,'best_score': model.best_score_,'best_params': model.best_params_})

df_results = pd.DataFrame(scores, columns=['model','best_score','best_params'])

df_results

,model,best_score,best_params
0,linear_regression,0.906220,{'fit_intercept': False}
1,ridge,0.907473,{'alpha': 1}
2,lasso,0.906236,{'alpha': 10}
3,random_forest,0.955317,"{'max_depth': 20, 'min_samples_split': 2, 'n_e..."
4,extra_trees,0.956123,"{'max_depth': 10, 'min_samples_split': 5, 'n_e..."
5,gradient_boosting,0.954993,"{'learning_rate': 0.1, 'max_depth': 3, 'n_esti..."
6,xgboost,0.955178,"{'learning_rate': 0.2, 'max_depth': 3, 'n_esti..."

In [63]:
model = RandomForestRegressor(
    max_depth=20,
    min_samples_split=5,
    n_estimators=200,
    random_state=42
)

model.fit(x, y)

RandomForestRegressor(max_depth=20, min_samples_split=5, n_estimators=200,
                      random_state=42)

In [64]:
model.score(x_test,y_test)

0.9899549909696752

In [65]:
from sklearn.metrics import r2_score, mean_absolute_error

y_pred = model.predict(x_test)

print("Test R2 score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))

Test R2 score: 0.9899549909696752
MAE: 178015.06021141045

In [66]:
import pickle

pickle.dump(model, open("model.pkl", "wb"))
pickle.dump(x.columns.tolist(), open("model_columns.pkl", "wb"))

In [1]:
import pickle
import pandas as pd

In [2]:
model = pickle.load(open("model.pkl", "rb"))
model_columns = pickle.load(open("model_columns.pkl", "rb"))

In [62]:
input_data = {
    "model_year": 2018,
    "milage": 45000,
    "transmission": 1,   # e.g. encoded as auto/manual
    "condition": 0,
    "no_of_seats": 5,
    "cc": 1000,
    "age": 6,
    "power_steering": 0,
    "push_start": 1,
    "power_seat": 1,
    "model_vitz": 1,
    "fuel_type_petrol": 1,
    "location_colombo": 1,
    "car/Suv/Sedan_sedan": 1,
    "ext_col_white": 1
}

In [63]:
# Create empty DataFrame with all training columns
df = pd.DataFrame([[0]*len(model_columns)], columns=model_columns)

# Update with provided values
for key, value in input_data.items():
    if key in df.columns:
        df.at[0, key] = value

In [64]:
df

,model_year,milage,transmission,condition,no_of_seats,cc,power_steering,push_start,power_seat,age,...,ext_col_dark blue,ext_col_desert sand mica,ext_col_grey,ext_col_lunar mist,ext_col_others,ext_col_pearl white,ext_col_red,ext_col_super white,ext_col_white,ext_col_wine red
0,2018,45000,1,0,5,1000,0,1,1,6,...,0,0,0,0,0,0,0,0,1,0

In [65]:
prediction = model.predict(df)
print("Predicted Price:", prediction[0])

Predicted Price: 14633196.13095238

In [33]:
# load model
model = pickle.load(open("model.pkl", "rb"))

# load columns
model_columns= pickle.load(open("model_columns.pkl", "rb"))

# Feature importance
importance = pd.Series(
    model.feature_importances_,
    index=model_columns   # use model_columns, not columns
).sort_values(ascending=False)

print(importance)

power_seat                        0.682045
model_year                        0.113894
age                               0.103657
model_toyota axio g grade         0.016981
milage                            0.016296
model_toyota premio g superior    0.009712
ext_col_pearl white               0.007984
model_vitz                        0.006835
model_toyota premio               0.004596
power_steering                    0.004318
condition                         0.003747
ext_col_white                     0.003568
model_toyota axio wxb             0.003141
fuel_type_hybrid                  0.002854
fuel_type_petrol                  0.002597
ext_col_wine red                  0.001919
cc                                0.001856
model_yaris                       0.001565
location_colombo                  0.001102
ext_col_black                     0.000936
location_gampaha                  0.000873
location_others                   0.000758
location_galle                    0.000755
transmission                      0.000726
location_kurunegala               0.000637
ext_col_others                    0.000607
ext_col_ash                       0.000499
fuel_type_diesel                  0.000487
model_aqua urban                  0.000465
location_maharagama               0.000395
location_panadura                 0.000383
model_corolla 121 x grade         0.000371
ext_col_dark blue                 0.000358
location_kadawatha                0.000352
location_kandy                    0.000350
location_nugegoda                 0.000346
location_matara                   0.000209
model_corolla 121 lx grade        0.000200
location_rathnapura               0.000200
ext_col_red                       0.000197
model_corolla 121 g grade         0.000186
location_kaluthara                0.000172
location_piliyandala              0.000144
model_aqua                        0.000142
location_kurunagala               0.000088
model_vitz safety                 0.000070
location_malabe                   0.000069
location_homagama                 0.000067
ext_col_super white               0.000066
ext_col_desert sand mica          0.000060
ext_col_grey                      0.000049
location_polonnaruwa              0.000049
ext_col_lunar mist                0.000031
push_start                        0.000017
car/sedan_car                     0.000006
no_of_seats                       0.000006
car/sedan_sedan                   0.000005
dtype: float64